/**
 * ABSistencia API
 * ABSistencia API for employee attendance management
 *
 * OpenAPI spec version: 1.4
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ModelsLocationRequest } from '../models/ModelsLocationRequest';
import { HttpFile } from '../http/http';

export class ModelsConvertAbsenceRequest {
    'absenceId': number;
    /**
    * RFC3339, optional
    */
    'checkinTime'?: string;
    'late'?: boolean;
    'lateReason'?: string;
    'locations': Array<ModelsLocationRequest>;
    'notes'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "absenceId",
            "baseName": "absence_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "checkinTime",
            "baseName": "checkin_time",
            "type": "string",
            "format": ""
        },
        {
            "name": "late",
            "baseName": "late",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "lateReason",
            "baseName": "late_reason",
            "type": "string",
            "format": ""
        },
        {
            "name": "locations",
            "baseName": "locations",
            "type": "Array<ModelsLocationRequest>",
            "format": ""
        },
        {
            "name": "notes",
            "baseName": "notes",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ModelsConvertAbsenceRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
