/**
 * ABSistencia API
 * ABSistencia API for employee attendance management
 *
 * OpenAPI spec version: 1.4
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ModelsLocationCatalogResponse } from '../models/ModelsLocationCatalogResponse';
import { HttpFile } from '../http/http';

export class ModelsBulkLocationResponse {
    'created'?: number;
    'errors'?: Array<string>;
    'failed'?: number;
    'locations'?: Array<ModelsLocationCatalogResponse>;
    'success'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "created",
            "baseName": "created",
            "type": "number",
            "format": ""
        },
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "failed",
            "baseName": "failed",
            "type": "number",
            "format": ""
        },
        {
            "name": "locations",
            "baseName": "locations",
            "type": "Array<ModelsLocationCatalogResponse>",
            "format": ""
        },
        {
            "name": "success",
            "baseName": "success",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ModelsBulkLocationResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
