/**
 * ABSistencia API
 * ABSistencia API for employee attendance management
 *
 * OpenAPI spec version: 1.4
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ModelsLocation } from '../models/ModelsLocation';
import { HttpFile } from '../http/http';

export class ModelsUserResponse {
    'active'?: boolean;
    'birthDate'?: string;
    'checkinStartTime'?: string;
    'checkoutEndTime'?: string;
    'cuil'?: string;
    /**
    * HR/extra fields
    */
    'dni'?: string;
    'email'?: string;
    'emailConfirmed'?: boolean;
    'endOfDayAbsenceDetection'?: boolean;
    'hireDate'?: string;
    'id'?: number;
    'location'?: ModelsLocation;
    'monthlyObjectiveDays'?: number;
    'name'?: string;
    'notes'?: string;
    'notificationOffsetMin'?: number;
    'officeDays'?: string;
    'pendingApproval'?: boolean;
    'phone'?: string;
    'picture'?: string;
    'role'?: string;
    'surname'?: string;
    'team'?: string;
    'teamsAccess'?: boolean;
    'timezone'?: string;
    'weeklyHours'?: number;
    'weeklyObjectiveDays'?: number;
    'zohoAccess'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "active",
            "baseName": "active",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "birthDate",
            "baseName": "birth_date",
            "type": "string",
            "format": ""
        },
        {
            "name": "checkinStartTime",
            "baseName": "checkin_start_time",
            "type": "string",
            "format": ""
        },
        {
            "name": "checkoutEndTime",
            "baseName": "checkout_end_time",
            "type": "string",
            "format": ""
        },
        {
            "name": "cuil",
            "baseName": "cuil",
            "type": "string",
            "format": ""
        },
        {
            "name": "dni",
            "baseName": "dni",
            "type": "string",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "emailConfirmed",
            "baseName": "email_confirmed",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "endOfDayAbsenceDetection",
            "baseName": "end_of_day_absence_detection",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "hireDate",
            "baseName": "hire_date",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "location",
            "baseName": "location",
            "type": "ModelsLocation",
            "format": ""
        },
        {
            "name": "monthlyObjectiveDays",
            "baseName": "monthly_objective_days",
            "type": "number",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "notes",
            "baseName": "notes",
            "type": "string",
            "format": ""
        },
        {
            "name": "notificationOffsetMin",
            "baseName": "notification_offset_min",
            "type": "number",
            "format": ""
        },
        {
            "name": "officeDays",
            "baseName": "office_days",
            "type": "string",
            "format": ""
        },
        {
            "name": "pendingApproval",
            "baseName": "pending_approval",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "phone",
            "baseName": "phone",
            "type": "string",
            "format": ""
        },
        {
            "name": "picture",
            "baseName": "picture",
            "type": "string",
            "format": ""
        },
        {
            "name": "role",
            "baseName": "role",
            "type": "string",
            "format": ""
        },
        {
            "name": "surname",
            "baseName": "surname",
            "type": "string",
            "format": ""
        },
        {
            "name": "team",
            "baseName": "team",
            "type": "string",
            "format": ""
        },
        {
            "name": "teamsAccess",
            "baseName": "teams_access",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "timezone",
            "baseName": "timezone",
            "type": "string",
            "format": ""
        },
        {
            "name": "weeklyHours",
            "baseName": "weekly_hours",
            "type": "number",
            "format": ""
        },
        {
            "name": "weeklyObjectiveDays",
            "baseName": "weekly_objective_days",
            "type": "number",
            "format": ""
        },
        {
            "name": "zohoAccess",
            "baseName": "zoho_access",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ModelsUserResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
