/**
 * ABSistencia API
 * ABSistencia API for employee attendance management
 *
 * OpenAPI spec version: 1.4
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export enum ModelsLocationType {
    LocationDomicilioRemotoDeclarado = 1,
    LocationDomicilioRemotoAlternativo = 2,
    LocationDomicilioCliente = 3,
    LocationOficinaABSTI = 4
}
