/**
 * ABSistencia API
 * ABSistencia API for employee attendance management
 *
 * OpenAPI spec version: 1.4
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ModelsLocationRequest } from '../models/ModelsLocationRequest';
import { HttpFile } from '../http/http';

export class ModelsUpdateLocationsRequest {
    'locations': Array<ModelsLocationRequest>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "locations",
            "baseName": "locations",
            "type": "Array<ModelsLocationRequest>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ModelsUpdateLocationsRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
