/**
 * ABSistencia API
 * ABSistencia API for employee attendance management
 *
 * OpenAPI spec version: 1.4
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ModelsCheckoutUpdateRequest {
    'checkoutStatus'?: string;
    'checkoutTime'?: string;
    'overtime'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "checkoutStatus",
            "baseName": "checkout_status",
            "type": "string",
            "format": ""
        },
        {
            "name": "checkoutTime",
            "baseName": "checkout_time",
            "type": "string",
            "format": ""
        },
        {
            "name": "overtime",
            "baseName": "overtime",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ModelsCheckoutUpdateRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
