/**
 * ABSistencia API
 * ABSistencia API for employee attendance management
 *
 * OpenAPI spec version: 1.4
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ModelsCheckinLocation } from '../models/ModelsCheckinLocation';
import { HttpFile } from '../http/http';

export class ModelsCheckinResponse {
    'absenceId'?: number;
    'checkoutStatus'?: string;
    'checkoutTime'?: string;
    'createdAt'?: string;
    'id'?: number;
    'late'?: boolean;
    'lateReason'?: string;
    'locations'?: Array<ModelsCheckinLocation>;
    'notes'?: string;
    'overtime'?: boolean;
    /**
    * return as RFC3339 string for API clients
    */
    'time'?: string;
    'userId'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "absenceId",
            "baseName": "absence_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "checkoutStatus",
            "baseName": "checkout_status",
            "type": "string",
            "format": ""
        },
        {
            "name": "checkoutTime",
            "baseName": "checkout_time",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "late",
            "baseName": "late",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "lateReason",
            "baseName": "late_reason",
            "type": "string",
            "format": ""
        },
        {
            "name": "locations",
            "baseName": "locations",
            "type": "Array<ModelsCheckinLocation>",
            "format": ""
        },
        {
            "name": "notes",
            "baseName": "notes",
            "type": "string",
            "format": ""
        },
        {
            "name": "overtime",
            "baseName": "overtime",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "time",
            "baseName": "time",
            "type": "string",
            "format": ""
        },
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ModelsCheckinResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
