/**
 * ABSistencia API
 * ABSistencia API for employee attendance management
 *
 * OpenAPI spec version: 1.4
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ModelsLocationRequest } from '../models/ModelsLocationRequest';
import { HttpFile } from '../http/http';

export class ModelsCheckinRequest {
    'lateReason'?: string;
    'locations': Array<ModelsLocationRequest>;
    'notes'?: string;
    /**
    * Optional, defaults to now
    */
    'time'?: string;
    /**
    * Optional, extracted from JWT if not provided
    */
    'userId'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "lateReason",
            "baseName": "late_reason",
            "type": "string",
            "format": ""
        },
        {
            "name": "locations",
            "baseName": "locations",
            "type": "Array<ModelsLocationRequest>",
            "format": ""
        },
        {
            "name": "notes",
            "baseName": "notes",
            "type": "string",
            "format": ""
        },
        {
            "name": "time",
            "baseName": "time",
            "type": "string",
            "format": ""
        },
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ModelsCheckinRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
