/**
 * ABSistencia API
 * ABSistencia API for employee attendance management
 *
 * OpenAPI spec version: 1.4
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export enum ModelsAbsenceType {
    AbsenceSick = 1,
    AbsenceVacation = 2,
    AbsencePersonal = 3,
    AbsenceUnauthorized = 4,
    AbsenceOther = 5
}
