/**
 * ABSistencia API
 * ABSistencia API for employee attendance management
 *
 * OpenAPI spec version: 1.4
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ModelsLocation } from '../models/ModelsLocation';
import { HttpFile } from '../http/http';

export class ModelsUser {
    'active'?: boolean;
    /**
    * Birth date
    */
    'birthDate'?: string;
    'checkinStartTime'?: string;
    'checkoutEndTime'?: string;
    /**
    * Tax ID
    */
    'cuil'?: string;
    /**
    * Additional fields from Excel files (optional, filled by HR)
    */
    'dni'?: string;
    /**
    * ID        uint      `gorm:\"primaryKey\"` // add manually if you want it in docs CreatedAt time.Time // add manually if you want it in docs UpdatedAt time.Time // add manually if you want it in docs DeletedAt gorm.DeletedAt `gorm:\"index\"` // add manually if you want it in docs
    */
    'email'?: string;
    'emailConfirmed'?: boolean;
    /**
    * Auto-detect absences at end of day
    */
    'endOfDayAbsenceDetection'?: boolean;
    /**
    * Hire date
    */
    'hireDate'?: string;
    'id'?: number;
    /**
    * Structured address as JSON string
    */
    'location'?: ModelsLocation;
    /**
    * Dias Objetivo MES
    */
    'monthlyObjectiveDays'?: number;
    'name'?: string;
    /**
    * General notes/aclaraciones
    */
    'notes'?: string;
    /**
    * minutes before check-in
    */
    'notificationOffsetMin'?: number;
    /**
    * Office days (e.g., \"MA/JU\", \"LU/MI\")
    */
    'officeDays'?: string;
    'pendingApproval'?: boolean;
    'phone'?: string;
    'picture'?: string;
    'role'?: string;
    'surname'?: string;
    /**
    * Team/Equipo
    */
    'team'?: string;
    /**
    * Teams access
    */
    'teamsAccess'?: boolean;
    'timezone'?: string;
    /**
    * Weekly working hours
    */
    'weeklyHours'?: number;
    /**
    * Dias Objetivo SEMANA
    */
    'weeklyObjectiveDays'?: number;
    /**
    * ZOHO access
    */
    'zohoAccess'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "active",
            "baseName": "active",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "birthDate",
            "baseName": "birth_date",
            "type": "string",
            "format": ""
        },
        {
            "name": "checkinStartTime",
            "baseName": "checkin_start_time",
            "type": "string",
            "format": ""
        },
        {
            "name": "checkoutEndTime",
            "baseName": "checkout_end_time",
            "type": "string",
            "format": ""
        },
        {
            "name": "cuil",
            "baseName": "cuil",
            "type": "string",
            "format": ""
        },
        {
            "name": "dni",
            "baseName": "dni",
            "type": "string",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "emailConfirmed",
            "baseName": "email_confirmed",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "endOfDayAbsenceDetection",
            "baseName": "end_of_day_absence_detection",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "hireDate",
            "baseName": "hire_date",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "location",
            "baseName": "location",
            "type": "ModelsLocation",
            "format": ""
        },
        {
            "name": "monthlyObjectiveDays",
            "baseName": "monthly_objective_days",
            "type": "number",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "notes",
            "baseName": "notes",
            "type": "string",
            "format": ""
        },
        {
            "name": "notificationOffsetMin",
            "baseName": "notification_offset_min",
            "type": "number",
            "format": ""
        },
        {
            "name": "officeDays",
            "baseName": "office_days",
            "type": "string",
            "format": ""
        },
        {
            "name": "pendingApproval",
            "baseName": "pending_approval",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "phone",
            "baseName": "phone",
            "type": "string",
            "format": ""
        },
        {
            "name": "picture",
            "baseName": "picture",
            "type": "string",
            "format": ""
        },
        {
            "name": "role",
            "baseName": "role",
            "type": "string",
            "format": ""
        },
        {
            "name": "surname",
            "baseName": "surname",
            "type": "string",
            "format": ""
        },
        {
            "name": "team",
            "baseName": "team",
            "type": "string",
            "format": ""
        },
        {
            "name": "teamsAccess",
            "baseName": "teams_access",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "timezone",
            "baseName": "timezone",
            "type": "string",
            "format": ""
        },
        {
            "name": "weeklyHours",
            "baseName": "weekly_hours",
            "type": "number",
            "format": ""
        },
        {
            "name": "weeklyObjectiveDays",
            "baseName": "weekly_objective_days",
            "type": "number",
            "format": ""
        },
        {
            "name": "zohoAccess",
            "baseName": "zoho_access",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ModelsUser.attributeTypeMap;
    }

    public constructor() {
    }
}
