/**
 * ABSistencia API
 * ABSistencia API for employee attendance management
 *
 * OpenAPI spec version: 1.4
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ModelsCheckinLocation {
    'checkinId'?: number;
    'createdAt'?: string;
    'endTime'?: string;
    'id'?: number;
    'locationDetail'?: string;
    'locationType': number;
    'startTime'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "checkinId",
            "baseName": "checkin_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "endTime",
            "baseName": "end_time",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "locationDetail",
            "baseName": "location_detail",
            "type": "string",
            "format": ""
        },
        {
            "name": "locationType",
            "baseName": "location_type",
            "type": "number",
            "format": ""
        },
        {
            "name": "startTime",
            "baseName": "start_time",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ModelsCheckinLocation.attributeTypeMap;
    }

    public constructor() {
    }
}
