/**
 * ABSistencia API
 * ABSistencia API for employee attendance management
 *
 * OpenAPI spec version: 1.4
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ModelsLocationType } from '../models/ModelsLocationType';
import { HttpFile } from '../http/http';

export class ModelsLocation {
    'calle'?: string;
    'ciudad'?: string;
    'codigoPostal'?: string;
    'numero'?: string;
    'pais'?: string;
    'piso'?: string;
    'provincia'?: string;
    'tipo'?: ModelsLocationType;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "calle",
            "baseName": "calle",
            "type": "string",
            "format": ""
        },
        {
            "name": "ciudad",
            "baseName": "ciudad",
            "type": "string",
            "format": ""
        },
        {
            "name": "codigoPostal",
            "baseName": "codigo_postal",
            "type": "string",
            "format": ""
        },
        {
            "name": "numero",
            "baseName": "numero",
            "type": "string",
            "format": ""
        },
        {
            "name": "pais",
            "baseName": "pais",
            "type": "string",
            "format": ""
        },
        {
            "name": "piso",
            "baseName": "piso",
            "type": "string",
            "format": ""
        },
        {
            "name": "provincia",
            "baseName": "provincia",
            "type": "string",
            "format": ""
        },
        {
            "name": "tipo",
            "baseName": "tipo",
            "type": "ModelsLocationType",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ModelsLocation.attributeTypeMap;
    }

    public constructor() {
    }
}


