/**
 * ABSistencia API
 * ABSistencia API for employee attendance management
 *
 * OpenAPI spec version: 1.4
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ModelsAbsenceResponse } from '../models/ModelsAbsenceResponse';
import { ModelsCheckinResponse } from '../models/ModelsCheckinResponse';
import { ModelsCheckoutResponse } from '../models/ModelsCheckoutResponse';
import { ModelsUserResponse } from '../models/ModelsUserResponse';
import { HttpFile } from '../http/http';

export class ModelsIndividualAttendanceResponse {
    'absence'?: ModelsAbsenceResponse;
    'checkin'?: ModelsCheckinResponse;
    'checkout'?: ModelsCheckoutResponse;
    'user'?: ModelsUserResponse;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "absence",
            "baseName": "absence",
            "type": "ModelsAbsenceResponse",
            "format": ""
        },
        {
            "name": "checkin",
            "baseName": "checkin",
            "type": "ModelsCheckinResponse",
            "format": ""
        },
        {
            "name": "checkout",
            "baseName": "checkout",
            "type": "ModelsCheckoutResponse",
            "format": ""
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "ModelsUserResponse",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ModelsIndividualAttendanceResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
