/**
 * ABSistencia API
 * ABSistencia API for employee attendance management
 *
 * OpenAPI spec version: 1.4
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ModelsCheckinConfigRequest {
    'checkinStartTime'?: string;
    'checkoutEndTime'?: string;
    'notificationOffsetMin'?: number;
    'timezone'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "checkinStartTime",
            "baseName": "checkin_start_time",
            "type": "string",
            "format": ""
        },
        {
            "name": "checkoutEndTime",
            "baseName": "checkout_end_time",
            "type": "string",
            "format": ""
        },
        {
            "name": "notificationOffsetMin",
            "baseName": "notification_offset_min",
            "type": "number",
            "format": ""
        },
        {
            "name": "timezone",
            "baseName": "timezone",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ModelsCheckinConfigRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
