/**
 * ABSistencia API
 * ABSistencia API for employee attendance management
 *
 * OpenAPI spec version: 1.4
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ModelsLocation } from '../models/ModelsLocation';
import { HttpFile } from '../http/http';

export class ModelsUserHRDetailsRequest {
    'approve'?: boolean;
    'birthDate'?: string;
    'cuil'?: string;
    'dni'?: string;
    'hireDate'?: string;
    'location'?: ModelsLocation;
    'monthlyObjectiveDays'?: number;
    'notes'?: string;
    'officeDays'?: string;
    'team'?: string;
    'teamsAccess'?: boolean;
    'weeklyHours'?: number;
    'weeklyObjectiveDays'?: number;
    'zohoAccess'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "approve",
            "baseName": "approve",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "birthDate",
            "baseName": "birth_date",
            "type": "string",
            "format": ""
        },
        {
            "name": "cuil",
            "baseName": "cuil",
            "type": "string",
            "format": ""
        },
        {
            "name": "dni",
            "baseName": "dni",
            "type": "string",
            "format": ""
        },
        {
            "name": "hireDate",
            "baseName": "hire_date",
            "type": "string",
            "format": ""
        },
        {
            "name": "location",
            "baseName": "location",
            "type": "ModelsLocation",
            "format": ""
        },
        {
            "name": "monthlyObjectiveDays",
            "baseName": "monthly_objective_days",
            "type": "number",
            "format": ""
        },
        {
            "name": "notes",
            "baseName": "notes",
            "type": "string",
            "format": ""
        },
        {
            "name": "officeDays",
            "baseName": "office_days",
            "type": "string",
            "format": ""
        },
        {
            "name": "team",
            "baseName": "team",
            "type": "string",
            "format": ""
        },
        {
            "name": "teamsAccess",
            "baseName": "teams_access",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "weeklyHours",
            "baseName": "weekly_hours",
            "type": "number",
            "format": ""
        },
        {
            "name": "weeklyObjectiveDays",
            "baseName": "weekly_objective_days",
            "type": "number",
            "format": ""
        },
        {
            "name": "zohoAccess",
            "baseName": "zoho_access",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ModelsUserHRDetailsRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
