/**
 * ABSistencia API
 * ABSistencia API for employee attendance management
 *
 * OpenAPI spec version: 1.4
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ModelsAbsenceType } from '../models/ModelsAbsenceType';
import { HttpFile } from '../http/http';

export class ModelsAbsenceResponse {
    'createdAt'?: string;
    'date'?: string;
    'fileUrl'?: string;
    'id'?: number;
    'reason'?: string;
    'type'?: ModelsAbsenceType;
    'userId'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "date",
            "baseName": "date",
            "type": "string",
            "format": ""
        },
        {
            "name": "fileUrl",
            "baseName": "file_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "reason",
            "baseName": "reason",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "ModelsAbsenceType",
            "format": ""
        },
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ModelsAbsenceResponse.attributeTypeMap;
    }

    public constructor() {
    }
}


