/**
 * ABSistencia API
 * ABSistencia API for employee attendance management
 *
 * OpenAPI spec version: 1.4
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ModelsLocationCatalogRequest } from '../models/ModelsLocationCatalogRequest';
import { HttpFile } from '../http/http';

export class ModelsBulkLocationRequest {
    'locations': Array<ModelsLocationCatalogRequest>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "locations",
            "baseName": "locations",
            "type": "Array<ModelsLocationCatalogRequest>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ModelsBulkLocationRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
