/**
 * ABSistencia API
 * ABSistencia API for employee attendance management
 *
 * OpenAPI spec version: 1.4
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ModelsAuditLog {
    /**
    * e.g. \"update_checkin\"
    */
    'action'?: string;
    /**
    * e.g. checkin ID
    */
    'entityId'?: number;
    /**
    * e.g. \"checkin\"
    */
    'entityType'?: string;
    'id'?: number;
    /**
    * JSON string of new checkin
    */
    'newValue'?: string;
    /**
    * JSON string of old checkin
    */
    'oldValue'?: string;
    'timestamp'?: string;
    /**
    * Who made the change (HR/admin)
    */
    'userEmail'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "action",
            "baseName": "action",
            "type": "string",
            "format": ""
        },
        {
            "name": "entityId",
            "baseName": "entity_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "entityType",
            "baseName": "entity_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "newValue",
            "baseName": "new_value",
            "type": "string",
            "format": ""
        },
        {
            "name": "oldValue",
            "baseName": "old_value",
            "type": "string",
            "format": ""
        },
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "string",
            "format": ""
        },
        {
            "name": "userEmail",
            "baseName": "user_email",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ModelsAuditLog.attributeTypeMap;
    }

    public constructor() {
    }
}
