/**
 * ABSistencia API
 * ABSistencia API for employee attendance management
 *
 * OpenAPI spec version: 1.4
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ModelsDailySummary {
    'createdAt'?: string;
    'date'?: string;
    'totalCheckins'?: number;
    'totalLate'?: number;
    'totalOnTime'?: number;
    'totalOvertime'?: number;
    'updatedAt'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "date",
            "baseName": "date",
            "type": "string",
            "format": ""
        },
        {
            "name": "totalCheckins",
            "baseName": "total_checkins",
            "type": "number",
            "format": ""
        },
        {
            "name": "totalLate",
            "baseName": "total_late",
            "type": "number",
            "format": ""
        },
        {
            "name": "totalOnTime",
            "baseName": "total_on_time",
            "type": "number",
            "format": ""
        },
        {
            "name": "totalOvertime",
            "baseName": "total_overtime",
            "type": "number",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ModelsDailySummary.attributeTypeMap;
    }

    public constructor() {
    }
}
