/**
 * ABSistencia API
 * ABSistencia API for employee attendance management
 *
 * OpenAPI spec version: 1.4
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ModelsLocationCatalogRequest {
    'address'?: string;
    'city'?: string;
    'country'?: string;
    'description'?: string;
    'isActive'?: boolean;
    'name': string;
    'type': ModelsLocationCatalogRequestTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "address",
            "baseName": "address",
            "type": "string",
            "format": ""
        },
        {
            "name": "city",
            "baseName": "city",
            "type": "string",
            "format": ""
        },
        {
            "name": "country",
            "baseName": "country",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "isActive",
            "baseName": "is_active",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "ModelsLocationCatalogRequestTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ModelsLocationCatalogRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum ModelsLocationCatalogRequestTypeEnum {
    Office = 'office',
    Client = 'client',
    Remote = 'remote',
    Other = 'other'
}

