import type { Metadata } from "next";
import "../app/ui/globals.css";
import { Montserrat, Mukta } from 'next/font/google';

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-montserrat',
});

const mukta = Mukta({
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700', '800'],
  variable: '--font-mukta',
});

export const metadata: Metadata = {
  title: "Presence Management Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body style={{ fontFamily: 'var(--font-montserrat)' }} className={`${montserrat.variable} ${mukta.variable}`}>
        {children}
      </body>
    </html>
  );
}
