import type { Metadata } from "next";
import "../app/globals.css";
import { Montserrat, Mukta } from 'next/font/google';
import { ThemeProvider } from "next-themes";

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-montserrat',
});

const mukta = Mukta({
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700', '800'],
  variable: '--font-mukta',
});

export const metadata: Metadata = {
  title: "Presence Management Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" suppressHydrationWarning>
      <body style={{ fontFamily: 'var(--font-montserrat)' }} className={`${montserrat.variable} ${mukta.variable}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
